apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: symfony
        image: dockydocky007/symfony
        ports:
        - containerPort: 80
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: symfony
spec:
  selector:
    app: symfony
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
